services:
  mysql:
    image: mysql:8.0
    container_name: gistify-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gistify
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  esummarizer:
    build: .
    image: sweekarshakya/esummarizer
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SERVER_ERROR_INCLUDE_BINDING_ERRORS: always
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - mysql
      - gistify

  gistify:
    image: sweekarshakya/gistify-microservice
    container_name: gistify-microservice-container
    ports:
      - "8000:8000"

volumes:
  mysql-data:
